management.tracing.sampling.probability=0
notificacion.service.url=http://localhost:8081
otel.traces.exporter=none
otel.metrics.exporter=none
otel.logs.exporter=none
jwt.secret=clave-super-secreta-sabana-2024-debe-ser-larga-minimo-32-chars
