apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-riesgo-to-notificacion
spec:
  podSelector:
    matchLabels:
      app: notificacion-service
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: riesgo-service
    ports:
    - protocol: TCP
      port: 8081
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
